version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: docker info >/dev/null 2>&1 || service docker start
      - run: npm install
      - run: npm test
